### ISSUE TITLE
Winminer 1.4.1 blocks not updateing

### ISSUE THREAD

**Issue by Opsjenar** [mochimodev/winminer#6]
New mochimo headless miner winminer 1.41 has a problem with updating blocks. Sometimes it updates a block after >45 seconds and sometimes it updates after 5+ minutes or sometimes it completely skips a block. Manual miner restart fixes probem and miner downloads correct block only for the problem to persist again...

![image](https://user-images.githubusercontent.com/44195088/56477817-03a6ed00-64aa-11e9-8e15-18e97ffdef49.png)

**Comment by chrisdigity** [comment]
Thanks @Opsjenar. Looks like it might be a bug with the update-monitor resetting it's `firstupdate` variable every second block or so once it's detected a block update.
https://github.com/mochimodev/winminer/blob/718830d7af6f8a805b18f1115ca3840b6ca35c79/winminer_v1/updatemonitor/updatemonitor.cpp#L62-L85

I'll fix it up and run some tests before sending out a new binary.

**Comment by chrisdigity** [comment]
The v1.4.2 release e8b5e1459456965b7f1c0377b69729a6ce3bc6f0 fixes this.
Thanks for raising the issue.
Closing
